Repository Capstone-FA25/booking-care-system-ui, pull requests merged in 2025-09, with the labels that each got.

#69 Merge Request hotfix/fix-re-render-search To develop
  src/components/SearchInput/SearchInput.tsx
  src/pages/UserProfile/DoctorSchedules/DoctorSchedules.module.scss
  src/pages/UserProfile/DoctorSchedules/DoctorSchedules.tsx
  src/pages/UserProfile/DoctorSchedules/index.ts
Labels: hoxfix

#72 Merge request from feature/appointment-ui_HieuMX into develop
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/components/DateCustomize.tsx
  src/layouts/BookingLayout/BookingLayout.tsx
  src/layouts/BookingLayout/index.ts
  src/layouts/MainLayout/MainLayout.tsx
  src/layouts/MainLayout/components/Footer/index.ts
  src/layouts/MainLayout/components/Header/Header.tsx
  src/layouts/MainLayout/components/Header/index.ts
  src/layouts/components/BookingFooter/BookingFooter.module.scss
  src/layouts/components/BookingFooter/BookingFooter.tsx
  src/layouts/components/BookingFooter/index.ts
  src/layouts/components/MainFooter/MainFooter.module.scss
  src/layouts/components/MainFooter/MainFooter.tsx
  src/layouts/components/MainFooter/index.ts
  src/layouts/components/MainHeader/MainHeader.module.scss
  src/layouts/components/MainHeader/MainHeader.tsx
  src/layouts/components/MainHeader/index.ts
  src/pages/Booking/Booking.module.scss
  src/pages/Booking/Booking.tsx
  src/pages/Booking/components/BookingAction/BookingAction.tsx
  src/pages/Booking/data/data.ts
  src/pages/Booking/data/mock.ts
  src/pages/Booking/index.ts
  src/pages/Booking/sections/BasicInfoSection/BasicInfoSection.tsx
  src/pages/Booking/sections/BasicInfoSection/index.ts
  src/pages/Booking/sections/ConfirmSection/ConfirmSection.module.scss
  src/pages/Booking/sections/ConfirmSection/ConfirmSection.tsx
  src/pages/Booking/sections/ConfirmSection/index.ts
  src/pages/Booking/sections/DateTimeSection/DateTimeSection.module.scss
  src/pages/Booking/sections/DateTimeSection/DateTimeSection.tsx
  src/pages/Booking/sections/DateTimeSection/components/SlotCategory/SlotCategory.tsx
  src/pages/Booking/sections/DateTimeSection/components/SlotCategory/index.ts
  src/pages/Booking/sections/DateTimeSection/components/SlotItem/SlotItem.module.scss
  src/pages/Booking/sections/DateTimeSection/components/SlotItem/SlotItem.tsx
  src/pages/Booking/sections/DateTimeSection/components/SlotItem/index.ts
  src/pages/Booking/sections/DateTimeSection/index.ts
  src/pages/Booking/sections/PaymentSection/PaymentSection.tsx
  src/pages/Booking/sections/PaymentSection/index.ts
  src/pages/Doctor/DoctorList/components/DoctorAppointmentBookingCard/DoctorAppointmentBookingCard.tsx
  src/routes/paths.ts
  src/routes/routeConfig.tsx
  src/services/discount.service.ts
  src/types/discount.types.ts
Labels: feature

#73 Merge request from feature/appointment-ui_HieuMX into develop
  src/enums/common.enums.ts
  src/enums/discount.enums.ts
  src/services/discount.service.ts
  src/store/slices/discount.slice.ts
  src/types/discount.types.ts
Labels: feature

#74 Merge request from hotfix/fix-bug-build-project_HieuMX into develop
  .gitignore
  src/assets/css/custom.css
  src/features/auth/LoginForm.tsx
  src/hooks/useAuth.tsx
  src/main.tsx
  src/store/selectors/discount.selectors.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.tsbuildinfo
Labels: hoxfix

#79 Merge request from config/config-cicd-pipiline_HieuMX into develop
  tsconfig.json
Labels: hoxfix

#80 Merge request from config/config-cicd-pipiline_HieuMX into develop
  .github/workflows/preview.yml
Labels: config

#89 Merge request from config/config-cicd-pipiline_HieuMX into develop
  sonar-project.properties
Labels: bug, hoxfix

#90 Merge Request feature/clinic-ui_HuyKV To develop
  src/components/TestimonialSection/TestimonialSection.module.scss
  src/components/TestimonialSection/TestimonialSection.tsx
  src/components/TestimonialSection/index.ts
  src/layouts/MainLayout/MainLayout.tsx
  src/pages/AboutUs/AboutUs.tsx
  src/pages/MedicalFacility/MedicalFacilityProfile/MedicalFacilityProfile.module.scss
  src/pages/MedicalFacility/MedicalFacilityProfile/MedicalFacilityProfile.tsx
  src/pages/MedicalFacility/MedicalFacilityProfile/components/BusinessHours/BusinessHours.tsx
  src/pages/MedicalFacility/MedicalFacilityProfile/components/BusinessHours/index.ts
  src/pages/MedicalFacility/MedicalFacilityProfile/components/HeroSection/HeroSection.module.scss
  src/pages/MedicalFacility/MedicalFacilityProfile/components/HeroSection/HeroSection.tsx
  src/pages/MedicalFacility/MedicalFacilityProfile/components/HeroSection/index.ts
  src/pages/MedicalFacility/MedicalFacilityProfile/components/Location/Location.module.scss
  src/pages/MedicalFacility/MedicalFacilityProfile/components/Location/Location.tsx
  src/pages/MedicalFacility/MedicalFacilityProfile/components/Location/index.ts
  src/pages/MedicalFacility/MedicalFacilityProfile/components/Overview/Overview.tsx
  src/pages/MedicalFacility/MedicalFacilityProfile/components/Overview/index.ts
Labels: feature

#94 Merge request from feature/home-page-clinics_HieuMX into develop
  src/components/Carousel/Carousel.tsx
  src/pages/Home/components/ClinicCaroulselItem/ClinicCaroulselItem.module.scss
  src/pages/Home/components/ClinicCaroulselItem/ClinicCaroulselItem.tsx
  src/pages/Home/components/SectionItem/SectionItem.tsx
Labels: feature

#96 Merge Request Feature/home_page_componen_ doctor-DatNNQ To develop
  src/pages/Booking/sections/ConfirmSection/ConfirmSection.tsx
  src/pages/Doctor/DoctorList/components/DoctorAppointmentBookingCard/DoctorAppointmentBookingCard.tsx
  src/pages/Home/Home.data.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/ClinicCaroulselItem/ClinicCaroulselItem.module.scss
  src/pages/Home/components/DoctorCarouselItem/DoctorCarouselItem.module.scss
  src/pages/Home/components/DoctorCarouselItem/DoctorCarouselItem.tsx
  src/pages/Home/components/DoctorCarouselItem/index.ts
  src/pages/Home/components/SectionItem/SectionItem.module.scss
  src/routes/paths.ts
  src/routes/routeConfig.tsx
Labels: feature

#100 Merge request from feature/custom-hook-use-api_HieuMX into develop
  docs/CUSTOM_API_HOOKS_GUIDE.md
  docs/CUSTOM_API_HOOKS_INTEGRATION.md
  src/components/SearchInput/SearchInput.module.scss
  src/features/auth/LoginForm.tsx
  src/hooks/useApi.tsx
  src/pages/Demo/Demo.tsx
  src/pages/Demo/list-components.ts
  src/pages/Doctor/DoctorList/DoctorList.tsx
  src/pages/Doctor/DoctorList/components/DoctorAppointmentBookingCard/DoctorAppointmentBookingCardSkeleton.tsx
  src/pages/Doctor/DoctorList/components/DoctorAppointmentBookingCard/index.ts
  src/pages/ScreenManagement/data/screens.data.ts
  src/routes/paths.ts
  src/routes/routeConfig.tsx
  src/types/user.type.ts
  tsconfig.app.json
  tsconfig.json
Labels: feature, config

#87 Merge Request feature/patient-appointments-ui_TamDN To develop
  src/pages/UserProfile/PatientAppointments/PatientAppointments.module.scss
  src/pages/UserProfile/PatientAppointments/PatientAppointments.tsx
  src/pages/UserProfile/PatientAppointments/components/AddReviewModal/AddReviewModal.module.scss
  src/pages/UserProfile/PatientAppointments/components/AddReviewModal/AddReviewModal.tsx
  src/pages/UserProfile/PatientAppointments/components/AddReviewModal/index.ts
  src/pages/UserProfile/PatientAppointments/components/AppointmentActions/AppointmentActions.tsx
  src/pages/UserProfile/PatientAppointments/components/AppointmentActions/index.ts
  src/pages/UserProfile/PatientAppointments/components/AppointmentCard/AppointmentCard.tsx
  src/pages/UserProfile/PatientAppointments/components/AppointmentCard/index.ts
  src/pages/UserProfile/PatientAppointments/components/AppointmentDetail/AppointmentDetail.module.scss
  src/pages/UserProfile/PatientAppointments/components/AppointmentDetail/AppointmentDetail.tsx
  src/pages/UserProfile/PatientAppointments/components/AppointmentDetail/components/CancelReasonModal/CancelReasonModal.module.scss
  src/pages/UserProfile/PatientAppointments/components/AppointmentDetail/components/CancelReasonModal/CancelReasonModal.tsx
  src/pages/UserProfile/PatientAppointments/components/AppointmentDetail/components/CancelReasonModal/index.ts
  src/pages/UserProfile/PatientAppointments/components/AppointmentDetail/index.ts
  src/pages/UserProfile/PatientAppointments/components/AppointmentFilters/AppointmentFilters.tsx
  src/pages/UserProfile/PatientAppointments/components/AppointmentFilters/index.ts
  src/pages/UserProfile/PatientAppointments/components/AppointmentHeader/AppointmentHeader.tsx
  src/pages/UserProfile/PatientAppointments/components/AppointmentHeader/index.ts
  src/pages/UserProfile/PatientAppointments/components/AppointmentTabs/AppointmentTabs.tsx
  src/pages/UserProfile/PatientAppointments/components/AppointmentTabs/index.ts
  src/pages/UserProfile/PatientAppointments/components/AppointmentTypes.ts
  src/pages/UserProfile/PatientAppointments/components/DateRangePicker/DateRangePicker.tsx
  src/pages/UserProfile/PatientAppointments/components/DateRangePicker/index.ts
  src/pages/UserProfile/ProfileSidebar/ProfileSidebar.tsx
Labels: feature

#111 Merge request from feature/fix_image_service_type_DatNNQ into develop
  src/pages/MedicalService/ServiceTypes/ServiceTypesPage.tsx
  src/pages/MedicalService/ServiceTypes/components/ServiceTypeCard.module.scss
  src/pages/MedicalService/ServiceTypes/components/ServiceTypeCard.tsx
Labels: bug

#114 Merge request from hotfix/fix-ui-search_TuDT_v2 into develop
  package-lock.json
  package.json
  src/assets/css/custom.css
  src/components/Carousel/Carousel.module.scss
  src/components/Carousel/Carousel.tsx
  src/components/DoctorCard/DoctorCard.module.scss
  src/components/DoctorCard/DoctorCard.tsx
  src/components/DoctorCard/index.ts
  src/components/HospitalCard/HospitalCard.module.scss
  src/components/HospitalCard/HospitalCard.tsx
  src/components/HospitalCard/index.ts
  src/components/SearchInput/SearchInput.module.scss
  src/components/SearchInput/SearchInput.tsx
  src/components/ServiceCard/ServiceCard.module.scss
  src/components/ServiceCard/ServiceCard.tsx
  src/components/ServiceCard/index.ts
  src/declarations.d.ts
  src/pages/Home/Home.data.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/Banner/Banner.module.scss
  src/pages/Home/components/Banner/Banner.tsx
  src/pages/Home/components/ClinicCaroulselItem/index.ts
  src/pages/Home/components/DoctorCarouselItem/DoctorCarouselItem.module.scss
  src/pages/Home/components/DoctorCarouselItem/index.ts
  src/pages/Home/components/ListServiceCategories/ListServiceCategories.tsx
  src/pages/Home/components/ListServiceCategories/index.ts
  src/pages/Home/components/SectionItem/SectionItem.tsx
  src/pages/Home/components/ServicesSection/ServiceSection.tsx
  src/pages/Home/components/ServicesSection/components/SectionHeader.tsx
  src/pages/Home/components/ServicesSection/components/ServiceCard.tsx
  src/pages/Home/components/SpecialtyCarouselItem/SpecialtyCarouselItem.tsx
  src/pages/SmartBooking/SmartBooking.module.scss
  src/pages/SmartBooking/SmartBooking.tsx
  src/pages/SmartBooking/components/EmptyState/EmptyState.module.scss
  src/pages/SmartBooking/components/EmptyState/EmptyState.tsx
  src/pages/SmartBooking/components/EmptyState/index.ts
  src/pages/SmartBooking/components/SearchBox/SearchBox.module.scss
  src/pages/SmartBooking/components/SearchBox/SearchBox.tsx
  src/pages/SmartBooking/components/SearchBox/index.ts
  src/pages/SmartBooking/components/TabNavigation/TabNavigation.module.scss
  src/pages/SmartBooking/components/TabNavigation/TabNavigation.tsx
  src/pages/SmartBooking/components/TabNavigation/index.ts
  src/pages/SmartBooking/index.ts
  src/pages/SmartBooking/smart-booking.mock.ts
  src/routes/paths.ts
  src/routes/routeConfig.tsx
  src/types/booking.ts
Labels: feature

#116 Merge request from hotfix/fix-ui-search_TuDT_v2 into develop
  src/components/ServiceCard/ServiceCard.module.scss
  src/components/ServiceCard/ServiceCard.tsx
Labels: hoxfix
