Repository Capstone-FA25/booking-care-system-ui, pull requests merged in 2025-08, with the labels that each got.

#23 [CONFIG] config import from root path
  package-lock.json
  package.json
  src/pages/Demo/list-components.ts
  src/routes/routeConfig.tsx
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: config

#24 [FIX] remove pre-push file
  .husky/pre-push
Labels: config

#30 Merge request from config/config-lint-precommit into develop
  eslint.config.js
  package.json
Labels: config

#26 Merge Request From user-profile-favourites To develop
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/Breadcrumb/index.ts
  src/pages/User_Profile/Favourite/Favourite.tsx
  src/pages/User_Profile/Favourite/components/DoctorCard/DoctorCard.module.scss
  src/pages/User_Profile/Favourite/components/DoctorCard/DoctorCard.tsx
  src/pages/User_Profile/Favourite/components/DoctorCard/index.ts
  src/pages/User_Profile/Favourite/components/RatingStars/RatingStars.tsx
  src/pages/User_Profile/Favourite/components/RatingStars/index.ts
  src/pages/User_Profile/Favourite/data/mockData.ts
  src/pages/User_Profile/Favourite/index.ts
  src/pages/User_Profile/PatientAppointments/PatientAppointments.tsx
  src/pages/User_Profile/PatientAppointments/index.ts
  src/pages/User_Profile/ProfileSidebar/ProfileSidebar.module.scss
  src/pages/User_Profile/ProfileSidebar/ProfileSidebar.tsx
  src/pages/User_Profile/ProfileSidebar/index.ts
  src/pages/User_Profile/UserProfile.tsx
  src/pages/User_Profile/index.ts
  src/routes/routeConfig.tsx
  tsconfig.node.json
Labels: feature

#47 Merge request from feature/button-common_HieuMX into develop
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/layouts/AuthLayout/AuthLayout.tsx
  src/pages/Authentication/ForgotPassword/ForgotPassword.tsx
  src/pages/Authentication/Login/Login.tsx
  src/pages/Authentication/Register/Register.tsx
  src/pages/Authentication/ResetPassword/ResetPassword.tsx
  src/styles/_auth.scss
Labels: feature

#48 Merge request from feature/header-footer-ui_HieuMX into develop
  src/layouts/MainLayout/MainLayout.module.scss
  src/layouts/MainLayout/MainLayout.tsx
  src/layouts/MainLayout/components/Footer/Footer.tsx
  src/layouts/MainLayout/components/Header/Header.tsx
  src/pages/Chat/Chat.tsx
Labels: feature

#56 Merge request from feature/doctor-profile into develop
  src/components/ReviewCard/ReviewCard.module.scss
  src/components/ReviewCard/ReviewCard.tsx
  src/components/ReviewCard/components/EditReplyForm/EditReplyForm.module.scss
  src/components/ReviewCard/components/EditReplyForm/EditReplyForm.tsx
  src/components/ReviewCard/components/EditReplyForm/index.ts
  src/components/ReviewCard/components/EditReviewForm/EditReviewForm.module.scss
  src/components/ReviewCard/components/EditReviewForm/EditReviewForm.tsx
  src/components/ReviewCard/components/EditReviewForm/index.ts
  src/components/ReviewCard/components/ReplyForm/ReplyForm.module.scss
  src/components/ReviewCard/components/ReplyForm/ReplyForm.tsx
  src/components/ReviewCard/components/ReplyForm/index.ts
  src/components/ReviewCard/index.ts
  src/pages/Doctor/DoctorProfile/DoctorProfile.tsx
Labels: feature

#55 Merge Request From input-common_HuyKV To develop
  src/components/Input/Input.tsx
  src/components/Input/index.ts
  src/layouts/AuthLayout/AuthLayout.module.scss
  src/pages/Authentication/ForgotPassword/ForgotPassword.tsx
  src/pages/Authentication/Login/Login.tsx
  src/pages/Authentication/Register/Register.tsx
  src/pages/Authentication/ResetPassword/ResetPassword.tsx
  src/pages/UserProfile/Setting/ChangePassword/ChangePassword.module.scss
  src/pages/UserProfile/Setting/ChangePassword/ChangePassword.tsx
  src/pages/UserProfile/Setting/ChangePassword/index.ts
  src/pages/UserProfile/Setting/Profile/Profile.module.scss
  src/pages/UserProfile/Setting/Profile/Profile.tsx
  src/pages/UserProfile/Setting/Profile/index.ts
  src/pages/UserProfile/Setting/Setting.module.scss
  src/pages/UserProfile/Setting/Setting.tsx
  src/pages/UserProfile/Setting/SettingsContainer/SettingsContainer.tsx
  src/pages/UserProfile/Setting/index.ts
  src/pages/UserProfile/UserProfile.tsx
  src/styles/_auth.scss
Labels: feature

#59 Merge request from hotfix/remove-recommend-review into develop
  src/components/ReviewCard/ReviewCard.tsx
  src/components/ReviewCard/components/EditReviewForm/EditReviewForm.tsx
Labels: hoxfix

#53 Merge Request From subscription-plans To develop
  package-lock.json
  package.json
  src/pages/Specialties/SpecialtiesList/SpecialtiesList.module.scss
  src/pages/Specialties/SpecialtiesList/SpecialtiesList.tsx
  src/pages/Specialties/SpecialtiesList/components/SpecialityCard.tsx
  src/pages/Specialties/SpecialtiesList/index.ts
  src/pages/SubscriptionPlans/SubscriptionPlans.tsx
  src/pages/SubscriptionPlans/components/SubscriptionPlanCard.module.scss
  src/pages/SubscriptionPlans/components/SubscriptionPlanCard.tsx
  src/pages/SubscriptionPlans/components/index.ts
  src/pages/SubscriptionPlans/index.ts
  src/routes/paths.ts
  src/routes/routeConfig.tsx
Labels: feature

#60 Merge Request From about-us-ui_HuyKV To develop
  src/pages/AboutUs/AboutUs.module.scss
  src/pages/AboutUs/AboutUs.tsx
  src/pages/AboutUs/components/AboutSection/AboutSection.tsx
  src/pages/AboutUs/components/AboutSection/index.ts
  src/pages/AboutUs/components/DoctorsSection/DoctorsSection.tsx
  src/pages/AboutUs/components/DoctorsSection/index.ts
  src/pages/AboutUs/components/FAQSection/FAQSection.module.scss
  src/pages/AboutUs/components/FAQSection/FAQSection.tsx
  src/pages/AboutUs/components/FAQSection/index.ts
  src/pages/AboutUs/components/TestimonialSection/TestimonialSection.module.scss
  src/pages/AboutUs/components/TestimonialSection/TestimonialSection.tsx
  src/pages/AboutUs/components/TestimonialSection/index.ts
  src/pages/AboutUs/components/WaySection/WaySection.tsx
  src/pages/AboutUs/components/WaySection/index.ts
  src/pages/AboutUs/components/WhyChooseSection/WhyChooseSection.tsx
  src/pages/AboutUs/components/WhyChooseSection/index.ts
  src/pages/AboutUs/index.ts
  src/routes/paths.ts
  src/routes/routeConfig.tsx
  src/styles/index.scss
Labels: feature

#67 Merge Request From fix-pagination To develop
  src/components/Pagination/Pagination.module.scss
  src/components/Pagination/Pagination.tsx
Labels: hoxfix

#66 Merge Request From doctor-list To develop
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/index.ts
  src/components/DoctorAppointmentBookingCard/DoctorAppointmentBookingCard.tsx
  src/components/SearchInput/SearchInput.module.scss
  src/components/SearchInput/SearchInput.tsx
  src/components/SearchInput/index.ts
  src/pages/Demo/list-components.ts
  src/pages/Doctor/DoctorList/DoctorList.module.scss
  src/pages/Doctor/DoctorList/DoctorList.tsx
  src/pages/Doctor/DoctorList/components/DoctorAppointmentBookingCard/DoctorAppointmentBookingCard.module.scss
  src/pages/Doctor/DoctorList/components/DoctorAppointmentBookingCard/DoctorAppointmentBookingCard.tsx
  src/pages/Doctor/DoctorList/components/DoctorAppointmentBookingCard/index.ts
  src/pages/Doctor/DoctorList/components/DoctorCard/DoctorCard.tsx
  src/pages/Doctor/DoctorList/components/DoctorCard/index.ts
  src/pages/Doctor/DoctorList/components/SideBar/SideBar.module.scss
  src/pages/Doctor/DoctorList/components/SideBar/SideBar.tsx
  src/pages/Doctor/DoctorList/components/SideBar/index.ts
  src/pages/Doctor/DoctorList/index.ts
  src/pages/Doctor/DoctorProfile/components/DoctorAvailability/DoctorAvailability.tsx
  src/pages/Doctor/SearchResult/SearchResult.module.scss
  src/pages/Doctor/SearchResult/SearchResult.tsx
  src/pages/Doctor/SearchResult/index.ts
  src/routes/paths.ts
  src/routes/routeConfig.tsx
Labels: feature
